; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sajatblog][download][type] = ""
projects[sajatblog][download][url] = ""
projects[sajatblog][type] = "module"

projects[features][version] = "2.10"

; Themes
projects[bootstrap][version] = "3.15"

projects[zen][version] = "6.4"
